filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/firewalld
    - /var/log/messages
    - /var/log/secure
    - /var/log/zabbix/zabbix*.log
    - /var/log/mysql/*.log
    - /var/log/httpd/*.log
    - /var/log/nginx/*.log
    - /var/log/grafana/*.log    
    
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
output.logstash:
  hosts: ["10.192.6.53:5044"]
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
logging.level: warning
